site_url: https://cozy-clothing.netlify.app

backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: 'product'
    label: 'Product'
    folder: 'content/product'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{name}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Price', name: 'price', widget: 'number' }
      - { label: 'Category', name: 'category', widget: 'relation', collection: 'category', search_fields: ['name'], value_field: 'name', display_fields: ['name'] }

  - name: 'category'
    label: 'Category'
    folder: 'content/category'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{name}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }