site_url: 'https://cozy-clothing.netlify.app'

backend:
  name: git-gateway
  branch: main

local_backend:
  allowed_hosts: ['192.168.0.123']

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - label: 'Data'
    name: 'data'
    files:
      - file: 'content/catalog/catalog.md'
        label: 'Catalog'
        name: 'catalog'
        allow_add: true
        fields:
        - label: 'Groups'
          name: 'groups'
          widget: 'list'
          allow_add: true
          fields:
              - label: 'Name'
                name: 'name'
                widget: 'string'
              - label: 'Description'
                name: 'description'
                widget: 'string'
        - label: 'Categories'
          name: 'categories'
          widget: 'list'
          allow_add: true
          fields:
              - label: 'Name'
                name: 'name'
                widget: 'string'
              - label: 'Description'
                name: 'description'
                widget: 'string'

# Products collection
  - name: 'product'
    label: 'Product'
    folder: 'content/product'
    create: true
    slug: '{{type}}-{{category}}-{{name}}'
    media_folder: ''
    public_folder: ''
    path: '{{type}}/{{category}}/{{name}}'
    editor:
      preview: true
    fields:
      - label: 'Name'
        name: 'name'
        widget: 'string'
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
      - label: 'Description'
        name: 'description'
        widget: 'string'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
      - label: 'Price'
        name: 'price'
        widget: 'number'
      - label: 'Category'
        name: 'category'
        widget: 'relation'
        collection: 'data'
        search_fields: ['categories.*.name']
        value_field: 'categories.*.name'
      - label: 'Group'
        name: 'group'
        widget: 'relation'
        collection: 'data'
        search_fields: ['groups.*.name']
        value_field: 'groups.*.name'
# ===========================================
